from __future__ import annotations

from ..config import OUTPUT_DIR
from ..field_routing import QueueAttractivenessField
from ..process_model import PROCESS_MODEL


DOWNSTREAM_BOARDING_QUEUES = PROCESS_MODEL.downstream_boarding_names
UPSTREAM_EXIT_QUEUES = PROCESS_MODEL.upstream_exit_names
GATE_QUEUE_NAMES = PROCESS_MODEL.entry_gate_names
EXIT_GATE_QUEUE_NAMES = PROCESS_MODEL.exit_gate_names
DEBUG_JSON = OUTPUT_DIR / "visual_demo_sim_debug.json"

STAGE_REPLAN_STALL_SECONDS = 6.0
STAGE_REPLAN_MIN_DELTA_M = 0.45
STAGE_REPLAN_LOAD_COST = 0.85
STAGE_REPLAN_QUEUE_COST = 0.65
STAGE_REPLAN_DISTANCE_COST = 0.22

QUEUE_TARGET_REPLAN_STALL_SECONDS = 8.0
QUEUE_REPLAN_MIN_IMPROVEMENT = 0.45
QUEUE_FIELD_SWITCHING_ENABLED = True
QUEUE_FIELD_SWITCHABLE_PREFIXES = ("boarding_door",)
QUEUE_FIELD_GRID_CELL_SIZE_M = 1.0
QUEUE_FIELD_DENSITY_RADIUS_CELLS = 2
QUEUE_FIELD_DENSITY_WEIGHT = 0.45
QUEUE_ATTRACTIVENESS_FIELD = QueueAttractivenessField()

ENTRY_GATE_CANDIDATES: dict[tuple[str, int], tuple[int, ...]] = {
    ("left", 0): (0, 1, 2),
    ("left", 1): (0, 1, 2),
    ("left", 2): (1, 2, 3),
    ("right", 0): (6, 7),
    ("right", 1): (6, 7),
    ("right", 2): (6, 7),
}

WAYPOINT_RADIUS_M = 1.0
GATE_DECISION_RADIUS_M = 3.4
TRANSFER_DECISION_RADIUS_M = 5.0
PLATFORM_DECISION_RADIUS_M = 2.2
RIGHT_ENTRY_CORRIDOR_RADIUS_M = 2.8
PLATFORM_APPROACH_RADIUS_M = 1.45
ALIGHTING_APPROACH_RADIUS_M = 4.0
ALIGHTING_EXIT_APPROACH_RADIUS_M = 3.4
ALIGHTING_VERTICAL_DECISION_RADIUS_M = 6.4
EXIT_CORRIDOR_RADIUS_M = 1.8
STATION_EXIT_BAND_HALF_SIZE_M = 7.0
POST_GATE_RADIUS_M = 1.15
ENTRY_GATE_PORTAL_RADIUS_M = 0.55
ELEVATOR_LOBBY_RADIUS_M = 1.6
BOARDING_SCREEN_DOOR_RADIUS_M = 0.55
BOARDING_VESTIBULE_RADIUS_M = 0.45
BOARDING_TRAIN_EXIT_HALF_SIZE_M = 0.35
ENTRY_DEMAND_HORIZON = 70.0
ELEVATOR_CHOICE_SHARE = 0.22
